config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_one_attached :profile_image
         has_many :books, dependent: :destroy
         
         validates :name, presence: true, length: {minimum:2, maximum:20}, uniqueness: true
         validates :introduction, length: {maximum:50}
         
         def get_profile_image(width, height)
           unless profile_image.attached?
             file_path = Rails.root.join('app/assets/images/default-image.jpg')
             profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
           end
           profile_image.variant(resize_to_limit: [width, height]).processed
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  
  def new
    @book = Book.new
  end
  
  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
    else
        @books = Book.all
        render :index
    end
  end
  
  def index
    @books = Book.all
    @user = current_user
  end
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def edit
    @book = Book.find(params[:id])
     if @book.user.id != current_user.id
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
       render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end  
    
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def index
    @user = current_user
    @users = User.all
    @books = @user.books
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
      
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @book do |f| %>
     
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title' %>
         
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body' %>
    
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', :class => 'btn btn-success' %>
        </div>
    
      <% end %>
      <%= link_to 'Show', book_path(@book) %>
      |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book %>
  <% if @book.errors.any? %>
  
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <% end %>
  
  <div class="row">

    <%= render 'users/list', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%=image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/list', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
      <tbody>
        <tr>
          <td>
              <%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_profile_image(100, 100) %>
          <br><%= @user.name %>
          <% end %>
          </td>
          <td><%= link_to @book.title %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
          </td>
          <td>
              <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger", data: { confirm: "本当に消しますか？" } %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
   </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book" aria-hidden="true"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcome to
        <i class="fas fa-book" aria-hidden="true"></i>
          <strong>Bookers</strong>
          !!
      </h1>
      <p>
        In
        <i class="fas fa-book" aria-hidden="true"></i>
          <strong>Bookers</strong>
          ,
      </p>
      <p>you can share and exchange your opinions, inpressions, and emotions </p>
      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign-in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-success btn-sm btn-block sign-up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/83484975db.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a href="https://dd395bbb0a2244cf9630f0e758761021.vfs.cloud9.ap-southeast-2.amazonaws.com/" class="navbar-brand">Bookers</a>
            
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
               <li>
                   <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                   <i class="fas fa-home" aria-hidden="true"></i>
                   Home
                   <% end %>
               </li>
               <li>
                   <%= link_to users_path, class:"nav-link text-light" do %>
                   <i class="fas fa-users" aria-hidden="true"></i>
                   Users
                   <% end %>
               </li>
               <li>
                   <%= link_to books_path, class:"nav-link text-light" do %>
                   <i class="fas fa-book-open" aria-hidden="true"></i>
                   Books
                   <% end %>
               </li>
               <li>
                   <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
                   <i class="fas fa-sign-out-alt" aria-hidden="true">
                   </i>
                    Log out
                    <% end %>
               </li>
               <% else %>
               <li>
                   <%= link_to root_path, class:"nav-link text-light" do %>
                   <i class="fas fa-home" aria-hidden="true"></i>
                   Home
                   <% end %>
               </li>
               <li>
                   <%= link_to about_path, class:"nav-link text-light" do %>
                       <i class="fas fa-link" aria-hidden="true"></i>
                        About
                    <% end %>
               </li>
               <li>
                   <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                   <i class="fas fa-user-plus" aria-hidden="true"></i>
                   Sign up
                   <% end %>
               </li>
               <li>
                   <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                   <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                   Log in
                   <% end %>
               </li>
               <% end %>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    
    <main>
       <%= yield %>
     </main>
       <footer>
         <div class="container mt-5">
           <div class="row">
    	    <div class="mx-auto">
    	      <p>CopyRight Infratop.inc</p>
    	    </div>
          </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <table class="table">
      <tbody>
        <tr>
          <th><%= image_tag @user.get_profile_image(100, 100) %></th>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    
    
      <div class="row">
  
          <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog" aria-hidden="true">
          </i>
          <% end %>
        </div>
    

      <h2 class="mt-3">New book</h2>
  
      <%= form_with model: Book.new do |f| %>
      
        <div class="form-group">
          <label for="book_title">Title</label>
          <br><%= f.text_field :title, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", :name => 'commit', :class => 'btn btn-success' %>
        </div>
    
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @user do |f| %>
    
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, :class => 'form-control name' %>
          </div>
  
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.file_field :profile_image, :class => 'form-control-file user_image' %>
          </div>
          
          <div class="from-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, :class => 'form-control introduction' %>
          </div>
          
          <div class="form-group">
          <%= f.submit "Update User", :class => 'btn btn-secondary' %>
          </div>
          
        <% end %>

      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

  <%= render 'list', user: @user, book: @book %>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(80, 80) %></td>
          <td><%= user.name %></td>
          <td><%=link_to 'Show', user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'list', user: @user, book: @book %>
    
    <div class="col-md-8 offset-md-1">
      
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |books| %>
            <tr>
              <td>
                <%= link_to user_path(books.user.id) do %>
                <%= image_tag @user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                 <%= link_to books.title, book_path(books) %>
              </td>
              <td>
                <%= books.body %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>